excluded:
    - Pods
    - SWIFTUI_MovieReviewTests
    - SWIFTUI_MovieReviewUITests
    - SWIFTUI_MovieReview/Application/SWIFTUI_MovieReviewApp.swift

disabled_rules:
- leading_whitespace
- trailing_whitespace
