excluded:
    - Pods
    - SWIFTUI_BookReviewUITests
    - SWIFTUI_BookReviewTests
    - SWIFTUI_BookReview/Application/SWIFTUI_MovieReviewApp.swift

disabled_rules:
- leading_whitespace
- trailing_whitespace
